services:
  markee:
    build:
      context: .
      dockerfile: Containerfile
    environment:
      - PORT=3200
      - NODE_ENV=production
    ports:
      - "3200:3200"
    networks:
      - cmsnet

networks:
  cmsnet:
    driver: bridge
